name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: clone private and Build
      run: |
        git git@github.com:joyoFeng/rust-actions.git --recursive
        cd rust-actions && cargo build --verbose
    
    - name: Run tests
      run: |
        echo "work directory: `pwd`
        cargo test --verbose
        
        
    - name: marked as success
      run: |
        echo "### Run code passed  :white_check_mark:" >> $GITHUB_STEP_SUMMARY
