name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        #with:
        #  path: master

      - name: Checkout private rep
        uses: actions/checkout@v3
        with:
          repository: joyoFeng/rust-actions
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          #path: my-rust-actions
      
      - name:  Build
        run: |
          cd rust-actions && cargo build --verbose
    
      - name: Run tests
        run: |
          echo "work directory: `pwd`"
          cd rust-actions && cargo test --verbose
        
        
      - name: marked as success
        run: |
          echo "### Run code passed  :white_check_mark:" >> $GITHUB_STEP_SUMMARY
